#ifndef BLE_APP_BLE_PERIPHERAL_BASIC_TRI_APP_PWOER_H
#define BLE_APP_BLE_PERIPHERAL_BASIC_TRI_APP_PWOER_H

/**
 * 初始化电源管理
 */
void power_management_init(void);

#endif //BLE_APP_BLE_PERIPHERAL_BASIC_TRI_APP_PWOER_H
