#ifndef BLE_APP_BLE_PERIPHERAL_BASIC_TRI_APP_TIMER_H
#define BLE_APP_BLE_PERIPHERAL_BASIC_TRI_APP_TIMER_H

/**
 * 初始化app timer相关
 */
void timers_init(void);

#endif //BLE_APP_BLE_PERIPHERAL_BASIC_TRI_APP_TIMER_H
